# Generated by Django 5.2 on 2026-05-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_hero_html',
            field=models.TextField(blank=True, help_text='Custom HTML for the profile hero section.', null=True),
        ),
    ]
