# Generated by Django 5.2 on 2026-05-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile_custom_hero_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_hero_css',
            field=models.TextField(blank=True, help_text="Custom CSS for the author's profile hero section.", null=True),
        ),
    ]
